# Generated by Django 4.1 on 2023-11-21 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Table1",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("dob", models.CharField(max_length=250)),
                ("age", models.PositiveIntegerField()),
                ("gender", models.CharField(max_length=10)),
                ("phone", models.PositiveIntegerField()),
                ("email", models.EmailField(max_length=254)),
                ("address", models.CharField(max_length=210)),
                ("department", models.CharField(max_length=100)),
                ("course", models.CharField(max_length=100)),
                ("purpose", models.CharField(max_length=250)),
                ("material", models.CharField(max_length=250)),
            ],
        ),
    ]
