# Generated by Django 4.1 on 2023-11-22 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="table1", name="age", field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="table1", name="phone", field=models.CharField(max_length=100),
        ),
    ]
