# Generated by Django 4.1 on 2023-11-22 07:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("school_app", "0002_alter_table1_age_alter_table1_phone"),
    ]

    operations = [
        migrations.CreateModel(
            name="Option",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("opt", models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name="table1",
            name="login_person",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RemoveField(model_name="table1", name="material",),
        migrations.AddField(
            model_name="table1",
            name="material",
            field=models.ManyToManyField(to="school_app.option"),
        ),
    ]
